# Generated by Django 4.2.5 on 2023-09-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.IntegerField()),
                ("contact_number", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "highest_qualification",
                    models.IntegerField(
                        choices=[
                            (1, "Btech"),
                            (2, "Mtech"),
                            (3, "Bsc"),
                            (4, "Msc"),
                            (5, "Bca"),
                            (6, "Mca"),
                        ]
                    ),
                ),
                ("year_of_passing", models.IntegerField()),
                ("cgpa", models.FloatField()),
                ("experience", models.IntegerField()),
                ("recent_job_responsibilities", models.TextField()),
                (
                    "application_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(2, "Accepted"), (3, "Rejected")],
                        null=True,
                    ),
                ),
                (
                    "interview_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "interview_result",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requirements.requirement",
                    ),
                ),
            ],
        ),
    ]
