# Generated by Django 4.2.5 on 2023-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0006_remove_candidate_interview_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="rank",
            field=models.CharField(default="R1", max_length=10),
            preserve_default=False,
        ),
    ]
