# Generated by Django 4.2.5 on 2023-09-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.IntegerField(
                        choices=[
                            (1, "Dotnet"),
                            (2, "Java"),
                            (3, "Python"),
                            (4, "Django"),
                            (5, "Flask"),
                            (6, "React"),
                        ]
                    ),
                ),
                ("vacancies", models.IntegerField()),
                ("closing_date", models.DateField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")]
                    ),
                ),
                ("min_experience", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
