# Generated by Django 4.2.5 on 2023-09-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0002_requirement_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="description",
            field=models.TextField(default="Description"),
        ),
    ]
