# Generated by Django 4.2.5 on 2023-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interviewobservation",
            old_name="interview_marks",
            new_name="marks",
        ),
        migrations.AddField(
            model_name="interviewobservation",
            name="result",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interviewschedule",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
