# Generated by Django 4.2.5 on 2023-09-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0007_candidate_rank"),
        ("interviews", "0003_alter_interviewobservation_result_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewobservation",
            name="interview",
        ),
        migrations.AddField(
            model_name="interviewobservation",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.candidate",
            ),
            preserve_default=False,
        ),
    ]
